[tool.coverage.report]
exclude_also = [
  'if __name__ == "__main__":',
]

[tool.mypy]
# Ensure we know what we do
warn_redundant_casts = true
warn_unused_ignores = true
warn_unused_configs = true

# Imports management
ignore_missing_imports = true
follow_imports = "skip"

# Ensure full coverage
disallow_untyped_defs = true
disallow_incomplete_defs = true
disallow_untyped_calls = true

# Restrict dynamic typing (a little)
# e.g. `x: List[Any]` or x: List`
# disallow_any_generics = true

strict_equality = true

[tool.pytest.ini_options]
log_level = "DEBUG"
pythonpath = "src"
addopts = """
  --cov-report=term-missing:skip-covered
  --cov=src
  --no-cov-on-fail
  --showlocals
  --strict-markers
  -r fE
  -vvv
  tests/
"""

[tool.ruff]
line-length = 120
indent-width = 4
target-version = "py312"

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

[tool.ruff.lint]
extend-select = ["ALL"]
ignore = [
  "COM812",   # conflict
  "D",        # Documentation, I know what I do!
  "ISC001",   # conflict
  "PLR2004",  # Magic value used in comparison
  "T201",     # `print()`
]
fixable = ["ALL"]

[tool.ruff.lint.per-file-ignores]
"src/translations.py" = [
  "E501",     # Line too long
  "RUF001",   # String contains ambiguous caracter
]
"tests/*" = [
  "ARG001",   # Unused function argument (because of pytest fixtures)
  "E501",     # Line too long
  "FBT001",   # Boolean-typed positional argument in function definition
  "S101",     # Use of `assert` detected
]
