name: Quality & Tests

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}-${{ github.event_name }}-${{ github.event_name != 'pull_request' && github.sha || '' }}
  cancel-in-progress: true

jobs:
  quality-and-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12.11"  # XXX: Keep in sync with the VPS
          cache: pip
      - name: Install requirements
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements-dev.txt
      - name: Check
        run: ./checks.sh
      - name: Unit tests
        run: python -m pytest
